JetBrains/bazel-bsp

.github/workflows/java.ci.yml, src/test/java/org/jetbrains/bsp/bazel/BazelBspServerTest.java, test.sh
1. Added file  ```.github/workflows/java.ci.yml``` with CI configuration which runs ```test.sh```
2. Commented out more test cases to make the test pass. 
3. Fixed target path in ```test.sh```.
=> Configure CI.

sample-repo/example/BUILD, sample-repo/example/ExampleTest.scala, src/main/java/org/jetbrains/bsp/bazel/commons/Constants.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/BspImplementationHub.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/impl/BuildServerImpl.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/impl/ScalaBuildServerImpl.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/resolvers/TargetsUtils.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/ScalaBuildServerService.java, src/test/java/org/jetbrains/bsp/bazel/BUILD, src/test/java/org/jetbrains/bsp/bazel/BazelBspServerTest.java, src/test/java/org/jetbrains/bsp/bazel/BazelBspServerTestData.java, third_party.bzl
my implementation of `buildTargetScalaTestClasses` method
=> buildTargetScalaTestClasses implementation 

buildAndRunLocally.sh
simple bash script to speed up development
=> script for building and running server

src/main/java/org/jetbrains/bsp/bazel/server/bep/BepDiagnosticsDispatcher.java, src/main/java/org/jetbrains/bsp/bazel/server/bep/BepServer.java, src/main/resources/log4j2.xml
I decided (just for the clarity) separate logs with level >=info to another file and creating file `.all.log` for all logs. It would be useful for checking entire flow without unnecessary events etc.
=> >=info logs are separate now

src/main/java/org/jetbrains/bsp/bazel/server/BUILD, src/main/java/org/jetbrains/bsp/bazel/server/BazelBspServer.java, src/main/java/org/jetbrains/bsp/bazel/server/bazel/BazelRunnerBuilder.java, src/main/java/org/jetbrains/bsp/bazel/server/bazel/params/BazelRunnerFlag.java, src/main/java/org/jetbrains/bsp/bazel/server/bazel/utils/BazelArgumentsUtils.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspCompilationManager.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspQueryManager.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/resolvers/TargetsUtils.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/JavaBuildServerService.java, src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/ScalaBuildServerService.java, src/test/java/org/jetbrains/bsp/bazel/BazelBspServerTestData.java
Dependencies must be fully built in order to guarantee the dependencies are all present for indexing.
Opening this one as a PR since I'm not sure if there's a better way of doing this.
=> Guarantee deps are built before finishing import.

src/main/java/org/jetbrains/bsp/bazel/commons/ListUtils.java, src/main/java/org/jetbrains/bsp/bazel/projectview/model/ProjectView.java, src/main/java/org/jetbrains/bsp/bazel/projectview/model/sections/ProjectViewSection.java, src/main/java/org/jetbrains/bsp/bazel/projectview/model/sections/specific/BUILD, src/main/java/org/jetbrains/bsp/bazel/projectview/model/sections/specific/DirectoriesSection.java, src/main/java/org/jetbrains/bsp/bazel/projectview/model/sections/specific/TargetsSection.java, src/main/java/org/jetbrains/bsp/bazel/projectview/parser/ProjectImportParser.java, src/main/java/org/jetbrains/bsp/bazel/projectview/parser/ProjectViewDefaultParserProvider.java, src/main/java/org/jetbrains/bsp/bazel/projectview/parser/ProjectViewImportParser.java, src/main/java/org/jetbrains/bsp/bazel/projectview/parser/ProjectViewParser.java, src/main/java/org/jetbrains/bsp/bazel/projectview/parser/ProjectViewParserImpl.java, src/main/java/org/jetbrains/bsp/bazel/projectview/parser/ProjectViewRawSectionParser.java, src/test/java/org/jetbrains/bsp/bazel/projectview/parser/BUILD, src/test/java/org/jetbrains/bsp/bazel/projectview/parser/ProjectViewParserImplTest.java, src/test/java/org/jetbrains/bsp/bazel/projectview/parser/ProjectViewParserMockTestImpl.java, src/test/java/org/jetbrains/bsp/bazel/projectview/parser/sections/specific/DirectoriesSectionParserTest.java, src/test/java/org/jetbrains/bsp/bazel/projectview/parser/sections/specific/TargetsSectionParserTest.java, src/test/java/org/jetbrains/bsp/bazel/projectview/parser/splitter/ProjectViewSectionSplitterTest.java, src/test/resources/projectview/projectView.bazelproject, src/test/resources/projectview/projectViewToImport.bazelproject, src/test/resources/projectview/projectViewWithImport.bazelproject, src/test/resources/projectview/projectViewWithoutDirectories.bazelproject, src/test/resources/projectview/projectViewWithoutTargets.bazelproject
Introducing `import path/to/file` support! It's quite basic, but works!
Sorry reviewers, but also I adjusted a bit code (mostly naming in tests).
=> [Projectview] import support

src/main/java/org/jetbrains/bsp/bazel/projectview/parser/sections/ProjectViewSectionParser.java, src/test/java/org/jetbrains/bsp/bazel/projectview/parser/ProjectViewParserImplTest.java, src/test/resources/projectview/projectViewWithTabs.bazelproject
Now parser supports also tabs in the projecview files
=> [fix] projectview - tab symbol parsing 

src/main/java/org/jetbrains/bsp/bazel/server/bazel/data/SemanticVersion.java, src/test/java/org/jetbrains/bsp/bazel/server/bazel/data/BUILD, src/test/java/org/jetbrains/bsp/bazel/server/bazel/data/SemanticVersionTest.java
fixes https://github.com/JetBrains/bazel-bsp/issues/65
=> [fix] Semantic version - more generic support

README.md, install.sh, src/main/java/org/jetbrains/bsp/bazel/install/Install.java, third_party.bzl
closes #69 
closes https://github.com/JetBrains/bazel-bsp/issues/48
=> installation process simplification

README.md
=> [fix] badges in readme

server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspQueryManager.java
Fixes https://github.com/JetBrains/bazel-bsp/issues/135
=> Build project during sync

CHANGELOG.md
just updating release date and adding https://github.com/JetBrains/bazel-bsp/pull/154 to changeling
=> [maintenance] release date update and a new fix in the changelog 

CHANGELOG.md, bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/utils/BazelStreamReader.java
Fixes https://github.com/JetBrains/bazel-bsp/issues/112
=> [fix] log messages are no longer trimmed

CHANGELOG.md, docs/scala.md
Technically it worked already for a while, but now it is official! 
---
closes https://github.com/JetBrains/bazel-bsp/issues/95
=> [feature] scala diagnostics work without a fork

README.md
`README` fix -- I broke it, I'm fixing it
=> [maintenance] `README` fix

server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/java/JdkResolver.java
Fixes an exception thrown in the cpp import test
=> Handle the case when there is no JDK in the project

WORKSPACE, server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/utils/BUILD, third_party.bzl
I added kotlin rules to the WORKSPACE, so now we can use kotlin rules in the project. Also, I bumped versions of dependencies. Also I updated one BUILD file
---
testing:
```
bazel build //...
bazel test //...
```
=> [maintenance] kotlin rules + versions bump

commons/src/main/java/org/jetbrains/bsp/bazel/commons/Constants.java, docs/dev/CONTRIBUTING.md
I temporary removed cpp from the supported languages list & updated contribution guide
=> [maintenance] temporary cpp is not supported & contribution guide update

server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/LanguagePluginsService.java, server/src/main/java/org/jetbrains/bsp/bazel/server/sync/model/Language.java
temporary cpp is not supported!
https://youtrack.jetbrains.com/issue/BAZEL-25
=> [maintenance] cpp is temporary not supported

executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/generator/DefaultProjectViewGenerator.kt, executioncontext/projectview/src/test/java/org/jetbrains/bsp/bazel/projectview/generator/DefaultProjectViewGeneratorTest.kt
well, i forgot about it
---
testing:
```
bazel test //executioncontext/projectview/...
```
=> [fix] now project view generator creates directories for project view file as well

server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/java/JdkResolver.java, server/src/main/java/org/jetbrains/bsp/bazel/server/sync/model/Project.java
Automagic serialization was doubling size of the file by serializing field that is derived from the actual state in the constructor.
=> [change] do not serialize label->module map

CHANGELOG.md
=> [maintenance] changelog update

executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/model/BUILD, executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/model/ProjectViewProvider.java
`ProjectViewProvider.java` has been removed - it was unused xd
=> [maintenance] unused `ProjectViewProvider` removal

bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/outputs/AsyncOutputProcessor.kt
1. When child process exited, `isRunning` flag was immediately set to
false, and the handlers were not called due to if(isRunning.get())
condition. It was very likely that a bunch of last lines were ignored
due to this.
2. In case stdout handlers execution took too long, the exception has
been silently ignored, despite very short timeout. So it was likely
that a line could be skipped even if the process was behaving correctly.
=> [fix] Ensure AsyncOutputProcessor deterministically processes stdout

server/src/main/java/org/jetbrains/bsp/bazel/server/BUILD
it's an old target, it doesnt work xd
=> [maintenance] removal of the unused target

executioncontext/workspacecontext/src/test/java/org/jetbrains/bsp/bazel/workspacecontext/BazelPathSpecMapperTest.kt
=> [maintenance] tests are even greener

bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/BazelRunner.kt, bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/BazelRunnerBuilder.kt, server/src/main/java/org/jetbrains/bsp/bazel/server/bep/BUILD, server/src/main/java/org/jetbrains/bsp/bazel/server/bep/BepServer.java, server/src/main/java/org/jetbrains/bsp/bazel/server/bloop/BloopExporter.java, server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspCompilationManager.java, server/src/main/java/org/jetbrains/bsp/bazel/server/sync/ExecuteService.kt
Previously it was created only on build
=> [fix] Create BEP server on demand for each Bazel call

CHANGELOG.md, server/src/main/java/org/jetbrains/bsp/bazel/server/diagnostics/DiagnosticBspMapper.kt, server/src/test/java/org/jetbrains/bsp/bazel/server/diagnostics/DiagnosticsServiceTest.kt
fix https://youtrack.jetbrains.com/issue/BAZEL-375
=> [fix] set PublishDiagnosticsParams.reset to be true | #BAZEL-375 Done

WORKSPACE, junit5.bzl
ohh i forgot about them, few bumps
=> [maintenance] junit5 deps bump

bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/params/BazelFlag.kt, bspcli/src/java/org/jetbrains/bsp/cli/Main.kt, bspcli/src/main/resources/log4j2_bspcli.xml, logger/src/main/java/org/jetbrains/bsp/bazel/logger/BspClientLogger.java, server/src/main/java/org/jetbrains/bsp/bazel/server/BazelBspServer.kt, server/src/main/java/org/jetbrains/bsp/bazel/server/ServerInitializer.kt, server/src/main/java/org/jetbrains/bsp/bazel/server/bep/BepOutputBuilder.java, server/src/main/java/org/jetbrains/bsp/bazel/server/bep/BepServer.java, server/src/main/java/org/jetbrains/bsp/bazel/server/bloop/BloopExporter.java, server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspAspectsManager.java, server/src/main/java/org/jetbrains/bsp/bazel/server/common/ServerContainer.kt, server/src/main/java/org/jetbrains/bsp/bazel/server/sync/MetricsLogger.kt, server/src/main/java/org/jetbrains/bsp/bazel/server/sync/ProjectResolver.kt
Example run:
`bazel run //bspcli -- <path-to-project> $PWD/metrics.txt`
=> [maintenance] Dump log metrics to file

WORKSPACE
Updates rules_bazel_integration_test from v0.17.0 to v0.18.0
=> [maintenance] updated rules_bazel_integration_test to v0.18.0

WORKSPACE
Updates com.google.protobuf:protobuf-java from 3.24.3 to 3.24.4
=> [maintenance] updated com.google.protobuf:protobuf-java to 3.24.4

MODULE.bazel, server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/dependencytree/BUILD
should fix issues with https://github.com/JetBrains/bazel-bsp/pull/501
=> [maintenance] bazel_dep `protobuf` removal

.teamcity/configurations/bazelBsp/bazelE2eTests.kts, .teamcity/settings.kts, MODULE.bazel, MODULE.bazel.lock, e2e/src/main/kotlin/org/jetbrains/bsp/bazel/BazelBspScalaProjectTest.kt, e2e/src/main/kotlin/org/jetbrains/bsp/bazel/base/BazelBspTestBaseScenario.kt, e2e/test-resources/enabled-rules-project/WORKSPACE
Previously there were not running on CI so it was possible they got broken in the meantime.
=> [maintenance] Fix enabled rules e2e test
