src/main/java/org/jetbrains/bsp/bazel/server/bsp/resolvers/ActionGraphParser.java
src/main/java/org/jetbrains/bsp/bazel/server/bsp/resolvers/TargetRulesResolver.java
src/main/java/org/jetbrains/bsp/bazel/server/bsp/resolvers/TargetsLanguageOptionsResolver.java
src/main/java/org/jetbrains/bsp/bazel/server/bsp/resolvers/TargetsRulesResolver.java
src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java
src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/JavaBuildServerService.java
src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/ScalaBuildServerService.java
src/test/java/org/jetbrains/bsp/bazel/BazelBspServerTest.java

Introducing ... `TargetsRuleResolver`!
It's a tiny change, but it'll be useful in `buildTargetScalaTestClasses` and `buildTargetScalaMainClasses` implementations.
Unfortunately, I tried, but I didn't manage to use it in `buildTargetResources` -- the logic is a bit too complicated, so I decided to leave it in the current state for a while. Nevertheless, I think that introduced mechanism could be extended and used there.
Also I thought that maybe it would be nice to introduce a [command pattern](https://en.wikipedia.org/wiki/Command_pattern) to this project -- api call = class. Logic, mostly, is very independent for every call (with few exceptions) so maybe it'd be nice to encapsulate it and get rid of ~ 400 lines classes. What do you think about it? If you think that it could be a good …

[Post BazelBuilder refactor part 2] TargetsRuleResolver

---

.bazelrc

So apparently error-prone is built into Bazel and provides a check for wildcard imports.
http://errorprone.info/docs/installation

Prohibit wildcard imports using error-prone

---

src/main/java/org/jetbrains/bsp/bazel/server/bep/BepServer.java

in the previous PR https://github.com/JetBrains/bazel-bsp/pull/71 i introduces java 11 feature while we are still using java 8

[fix] java 8 feature fix

---

WORKSPACE

sometimes (mainly on the GitHub CI) we had some warnings from bazel about rules from the WORKSPACE file. This PR fixes it

[fix] bazel WORKSPACE warnings fix

---

bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/BazelRunner.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java

One command that doesn't accept arguments at all (only flags) is `bazel clean`.
Fixes #119.

Allow running a Bazel command without [positional] arguments

---

CHANGELOG.md
commons/src/main/java/org/jetbrains/bsp/bazel/commons/Constants.java
server/src/main/java/org/jetbrains/bsp/bazel/server/BazelBspServer.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/utils/SourceRootGuesser.java
server/src/test/java/org/jetbrains/bsp/bazel/server/bsp/utils/BUILD
server/src/test/java/org/jetbrains/bsp/bazel/server/bsp/utils/SourceRootGuesserTest.java

Fixes #115.
Credits for the idea go to @lukaszwawrzyk.

Better heuristics for guessing source roots

---

bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/BazelRunner.java
install/src/main/java/org/jetbrains/bsp/bazel/install/Install.java
projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/parser/ProjectViewDefaultParserProvider.java
server/src/main/java/org/jetbrains/bsp/bazel/server/ServerInitializer.java
server/src/test/java/org/jetbrains/bsp/bazel/server/bsp/utils/SourceRootGuesserTest.java

Fixes #122.
The goal of this PR is to allow creating the bsp/intellij project root in different location than the repository root.
Example locations could be <REPO>/bsp-projects/<PROJ> or <REPO>/../bsp-projects/<PROJ>.
I imagine it would be used through a wrapper like `bazel idea --bsp --name myproject --targets //target_a/... //target_b/...`, and such wrapper would manage where this directory is, if project already exists, auto generating name and similar things. But first, the server needs to support it.
I made a distinction between `workspace root` (bazel workspace root) and `bsp project root` (root directory for .bsp, .idea, .bazelbsp, projectview.bazelview files). I added workspace root as startup arg of the server and it is set up by the installer. It is used as a directory where …

Handle multiple projects in one workspace

---

server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/resolvers/TargetsLanguageOptionsResolver.java

When bsp server asks for compile classpath and ouput (javac/scalac options), the server returns a list of identical responses except for class directory. There is one object per output. Bazel reports like 6 outputs jarname.jar jarname-src.jar jarname-native-headers.jar jarname-hjar.jar etc.
On the client side just one response per target is expected. The whole response is converted to map from target id to data which results basically in selecting random/last output from response. 
According to how bazel names these jars and sorting of strings works, my PR will select just the jarname.jar and return single response for a target.

Return only the relevant output jar rather than 5-6 jars 

---

commons/src/main/java/org/jetbrains/bsp/bazel/commons/Constants.java
e2e/src/main/java/org/jetbrains/bsp/bazel/BazelBspSampleRepoTest.java
e2e/src/main/java/org/jetbrains/bsp/bazel/base/BazelBspTestBaseScenario.java
e2e/src/main/java/org/jetbrains/bsp/bazel/base/BazelBspTestScenarioStep.java
install/src/main/java/org/jetbrains/bsp/bazel/install/aspects.bzl
server/src/main/java/org/jetbrains/bsp/bazel/server/BazelBspServer.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bep/BepServer.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspAspectsManager.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/JvmBuildServerService.java

TargetsLanguageOptionsResolver that I am using returns all outputs and inputs for given target. This includes source jars that are useless at runtime as well as hjars and ijars. For example this causes junit classes without bodies to appear on classpath and shadowing the actual implementation which fails tests at runtime. 
I proposed a simple workaround here, to just remove jars that *look like* not relevant for runtime. This fixed test running for me.
I feel like it is not *the solution*, I would like to know from bazel if a jar is relevant for runtime or not, but I don't know how to get  this.
I see that we might try the custom aspect approach from google's plugin: https://github.com/bazelbuild/intellij/blob/master/aspect/java_classpath.bzl but I hoped it should be easier than custom …

Filter out non runtime jars for running apps and tests

---

CHANGELOG.md
install.sh
server/src/main/java/org/jetbrains/bsp/bazel/server/bep/BepServer.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bep/parsers/error/BUILD
server/src/main/java/org/jetbrains/bsp/bazel/server/bep/parsers/error/FileDiagnostic.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bep/parsers/error/StderrDiagnosticsParser.java
server/src/test/java/org/jetbrains/bsp/bazel/server/bep/parsers/error/BUILD
server/src/test/java/org/jetbrains/bsp/bazel/server/bep/parsers/error/FileDiagnosticTest.java
server/src/test/java/org/jetbrains/bsp/bazel/server/bep/parsers/error/StderrDiagnosticsParserTest.java

This is not the best possible solution, entire event handling should be done better, but for now it should be sufficient.
---
Fixes https://github.com/JetBrains/bazel-bsp/issues/67 
Fixes https://github.com/JetBrains/bazel-bsp/issues/111
Fixes https://github.com/JetBrains/bazel-bsp/issues/145
---
testing:
```
bazel test //server/src/test/java/org/jetbrains/bsp/bazel/server/bep/parsers/error:FileDiagnosticTest
bazel test //server/src/test/java/org/jetbrains/bsp/bazel/server/bep/parsers/error:StderrDiagnosticsParserTest
```
and manually on some sample repo like [this](https://github.com/kpodsiad/bazel-scala)

[fix] error diagnostics with correct position

---

bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/BazelDataResolver.java
bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/data/BazelData.java
install/src/main/java/org/jetbrains/bsp/bazel/install/Install.java
server/src/main/java/org/jetbrains/bsp/bazel/server/BUILD
server/src/main/java/org/jetbrains/bsp/bazel/server/BazelBspServer.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspAspectsManager.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspJvmTargetManager.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspScalaTargetManager.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelCppTargetManager.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/CppBuildServerService.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/JvmBuildServerService.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/utils/InternalAspectsResolver.java
server/src/test/java/org/jetbrains/bsp/bazel/server/bsp/utils/BUILD
server/src/test/java/org/jetbrains/bsp/bazel/server/bsp/utils/InternalAspectsResolverTest.java

Path to aspects was absolute and hardcoded in multiple places as //.bazelbsp:aspects.bzl%ASPECT_NAME and this only works if workspace root == bsp root. I fixed this and made some refactoring.

Handle aspects when multiple projects are in workspace

---

CHANGELOG.md
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/BazelProjectMapper.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/java/JavaLanguagePlugin.java

Traversing dependency graph the way it was implemented (very naively) is painfully slow, which can be noticed on bigger projects. It would be nice to have a graph built once and just take all direct deps from it based on condition to not duplicate them.
As a fairly reasonable workaround, I just take transitive source deps directly from bazel where they are already computed anyway. BSP client will deduplicate and group it anyway.

[change] improve source dependencies performance

---

server/src/main/java/org/jetbrains/bsp/bazel/server/sync/TargetKindResolver.java

Users can manually mark the target as excluded from IDE by using tags. BSP also supports NO_IDE tag, we just need to make sure it is forwarded.

[change] forward the no-ide tag from bazel to bsp client

---

e2e/src/main/java/org/jetbrains/bsp/bazel/BazelBspSampleRepoTest.java

I accidentally removed too much deps. In fact if test would check if each of targets depends on all of these source jars, it would pass, but I test it on purpose for deps/deeper only, because this is enough. These deps would come transitively if not returned directly.

[change] dependency sources test fix

---

CHANGELOG.md
bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/outputs/AsyncOutputProcessor.java

bazel outputs identical lines, one after another. This is cosmetic change, there is no point to show them, they only make everything less clear.

[change] do not forward duplicate lines to bsp-client

---

CHANGELOG.md
install/src/main/java/org/jetbrains/bsp/bazel/install/aspects.bzl

We found out that import fails for projects with Kotlin libraries because of aspects, this PR fixes it
---
#BAZEL-16 Fixed
---
testing:
manual with some Kotlin rules

[fix] kotlin targets don't break import

---

CHANGELOG.md
install/src/main/java/org/jetbrains/bsp/bazel/install/cli/CliOptionsProvider.java

Now installer maps the path to the project view file into absolute path - it means that this path is resolved using PWD of the installer, now PWD of the server
---
[#BAZEL-20](https://youtrack.jetbrains.com/issue/BAZEL-20)
---
testing: manual : (

[fix] project view path is mapped to the absolute path in the installer | #BAZEL-20

---

server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/scala/ScalaSdkResolver.java

Otherwise it catches strange jars like scala-library-indexing_interface_2.12-1.1.0.jar - blocks importing google's bazel plugin

[change] fix scala version regex

---

CHANGELOG.md
executioncontext/projectview/README.md
executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/generator/DefaultProjectViewGenerator.kt
executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/generator/sections/ProjectViewExcludableListSectionGenerator.kt
executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/generator/sections/ProjectViewSingletonSectionGenerator.kt
executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/model/ProjectView.kt
executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/model/sections/ProjectViewExcludableListSection.kt
executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/model/sections/ProjectViewSingletonSection.kt
executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/parser/DefaultProjectViewParser.kt
executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/parser/sections/ProjectViewExcludableListSectionParser.kt
executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/parser/sections/ProjectViewSingletonSectionParser.kt
executioncontext/projectview/src/test/java/org/jetbrains/bsp/bazel/projectview/generator/DefaultProjectViewGeneratorTest.kt
executioncontext/projectview/src/test/java/org/jetbrains/bsp/bazel/projectview/model/ProjectViewBuilderTest.kt
executioncontext/projectview/src/test/java/org/jetbrains/bsp/bazel/projectview/parser/DefaultProjectViewParserTest.kt
executioncontext/projectview/src/test/resources/projectview/file1.bazelproject
executioncontext/projectview/src/test/resources/projectview/file2.bazelproject
executioncontext/projectview/src/test/resources/projectview/file3.bazelproject
executioncontext/projectview/src/test/resources/projectview/file4ImportsFile1.bazelproject
executioncontext/projectview/src/test/resources/projectview/file7ImportsFile1.bazelproject
executioncontext/projectview/src/test/resources/projectview/file8ImportsEmpty.bazelproject
executioncontext/projectview/src/test/resources/projectview/without/derive_targets_from_directories.bazelproject
executioncontext/projectview/src/test/resources/projectview/without/directories.bazelproject
executioncontext/workspacecontext/src/main/java/org/jetbrains/bsp/bazel/workspacecontext/TargetsSpec.kt
executioncontext/workspacecontext/src/test/java/org/jetbrains/bsp/bazel/workspacecontext/BazelPathSpecMapperTest.kt
executioncontext/workspacecontext/src/test/java/org/jetbrains/bsp/bazel/workspacecontext/TargetsSpecMapperTest.kt
executioncontext/workspacecontext/src/test/java/org/jetbrains/bsp/bazel/workspacecontext/WorkspaceContextConstructorTest.kt
install/src/main/java/org/jetbrains/bsp/bazel/install/ProjectViewCLiOptionsProvider.kt
install/src/main/java/org/jetbrains/bsp/bazel/install/cli/CliOptions.kt
install/src/main/java/org/jetbrains/bsp/bazel/install/cli/CliOptionsProvider.kt
install/src/test/java/org/jetbrains/bsp/bazel/install/cli/CliOptionsProviderTest.kt

Added parsing directories and derive_targets_from_directories section from project view file and mapping those into targets
---
https://youtrack.jetbrains.com/issue/BAZEL-33
https://youtrack.jetbrains.com/issue/BAZEL-55

[feature] `directories` and `derive_targets_from_directories` sections are now supported in project view

---

server/src/main/java/org/jetbrains/bsp/bazel/server/sync/BazelPathsResolver.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/BazelProjectMapper.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/IntelliJProjectTreeViewFix.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/scala/ScalaSdkResolver.java

Path resolution is the heaviest part of the whole bsp mappping process (and vavr collections). Paths.get and Path.toUri calls take a lot of time. This can be optimized. 
Check out these stats
Building project with aspect completed in 3m 30s
Reading aspect output paths completed in 593ms
Parsing aspect outputs completed in 20s
Mapping to internal model completed in 39.3s
**Collected uris in total: 4009673
Collected unique uris in total: 15665**
Saving project to local cache completed in 4s
Reduces mapping to internal model by 50% for me.

[change] cache uris and paths in BazelPathsResolver

---

e2e/src/main/java/org/jetbrains/bsp/bazel/BazelBspLocalJdkTest.kt
e2e/src/main/java/org/jetbrains/bsp/bazel/BazelBspRemoteJdkTest.kt
e2e/src/main/java/org/jetbrains/bsp/bazel/BazelBspSampleRepoTest.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/BazelProjectMapper.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/EmptyLanguagePlugin.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/JVMLanguagePluginParser.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/LanguagePlugin.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/cpp/CppLanguagePlugin.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/java/JavaLanguagePlugin.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/scala/ScalaLanguagePlugin.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/thrift/ThriftLanguagePlugin.java
server/src/test/java/org/jetbrains/bsp/bazel/server/sync/languages/BUILD
server/src/test/java/org/jetbrains/bsp/bazel/server/sync/languages/LanguagePluginServiceTest.kt

IntelliJ supports a package prefix attribute on source directories. The BSP spec and Scala plugin BSP client supports this data as well, but the implementation in bazel-bsp seems to not infer the prefix correctly. [BAZEL-54](https://youtrack.jetbrains.com/issue/BAZEL-54/package-prefix-in-bazel-bsp-not-inferred-correctly)
Added parsing of file looking for packages declaration for every compatible language.

[change] added parsing for package prefixes

---

CHANGELOG.md
install/src/main/java/org/jetbrains/bsp/bazel/install/ProjectViewCLiOptionsProvider.kt
install/src/main/java/org/jetbrains/bsp/bazel/install/cli/CliOptions.kt
install/src/main/java/org/jetbrains/bsp/bazel/install/cli/CliOptionsProvider.kt
install/src/test/java/org/jetbrains/bsp/bazel/install/cli/CliOptionsProviderTest.kt

Introducing `--excluded-targets` and `--excluded-directories` flags instead of `-` prefix in cli project view generator
one day in the future we'll replace this apache cli parser with some kotlin parser - but not today xd
---
https://youtrack.jetbrains.com/issue/BAZEL-103/cli-short-option-parsing-bug
---

[fix] excluded targets and directories cli flags bug fix

---

server/src/main/java/org/jetbrains/bsp/bazel/server/common/ServerContainer.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/ProjectResolver.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/TargetInfoReader.kt

I moved reading target info from ProjectResolver class to new ProjectFileParser class and added HashMap caching info about Target with LastModified timestamps for every file to optimise parsing file that hadn't had any changes between incremental Syncs. Thank to that I was able to reduce the time of next sync (for example from ca. 20s in first import to ca. 300ms to next import without changes in files)

[change] added cache of targets info in incremental syncs

---

README.md

coursier needs a `--` after the class to launch and arguments

[maintenance] fix coursier command in README

---

server/src/main/java/org/jetbrains/bsp/bazel/server/bloop/BspModuleExporter.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/bloop/Naming.java

https://github.com/JetBrains/bazel-bsp/commit/57c2c19c33e3055adeba9d043d9269435ddb83ac removed the override of Label.toString, which broke its representation in a couple places, this changes them to use `.value` instead.

[fix] don't use Label.toString now that it's no longer overriden

---

CHANGELOG.md
install/src/main/java/org/jetbrains/bsp/bazel/install/cli/CliOptionsProvider.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/ProjectResolver.kt

- all installer flags are using kebab case now
- `--bazel-workspace` help is now correct
- typo in logs is fixed
is it a breaking change because of the flags? XD

[fix] kebab case in the installer flags & help typo fix & log typo fix

---

CHANGELOG.md
bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/BazelRunner.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/BazelBspServer.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/ServerInitializer.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/common/ServerContainer.kt

so now we are using workspace root always - even if user specifies a directory inside the workspace

[fix] workspace root is always used as a bazel directory

---

CHANGELOG.md
server/src/main/java/org/jetbrains/bsp/bazel/server/bloop/BloopExporter.java
server/src/test/java/org/jetbrains/bsp/bazel/server/bloop/BUILD
server/src/test/java/org/jetbrains/bsp/bazel/server/bloop/BloopExporterTest.kt

#261 accidentally switched the predicate to test if any transitive targets failed, resulting in direct failures causing project imports to fail, and transitive ones to succeed.  This is the opposite of what should happen.
This changes it back, and adds a unit test.

[fix] fix transitive target failure check in bloop export

---

server/src/main/java/org/jetbrains/bsp/bazel/server/bloop/ReGlobber.kt
server/src/test/java/org/jetbrains/bsp/bazel/server/bloop/ReGlobberTest.kt

This improves the logic in the reglobber to be smarter if multiple targets share the same base path, for example, if multiple targets are in the same BUILD file in `root`, and have targets that look like:
```
scala_library(
name = 'a',
srcs = [globs("a/src/main/**.scala")]
)
scala_library(
name = 'b',
srcs = [globs("b/src/main/**.scala")]
)
```
Previously the logic would end up with both `a` and `b` having a glob of `**.scala`, the new logic in this review changes it so a would be a glob with root directory of `root/a/src/main` and b of `root/b/src/main`.

[change] improve reglobbing logic for bloop reglobbing

---

bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/BazelInfoResolver.kt
bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/BazelProcess.kt
bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/outputs/AsyncOutputProcessor.kt
bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/outputs/OutputProcessor.kt
bazelrunner/src/main/java/org/jetbrains/bsp/bazel/bazelrunner/outputs/SyncOutputProcessor.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspCompilationManager.java

#279 re-introduced a bug on linux where the OutputProcessor can hang for up to 45 seconds waiting for the process (which has already existed) to exit.
This change adds a different type of OutputProcessor for commands that need to wait (bazel info, etc) to receive the full output, vs ones that don't (piping the build logs to the output handlers).

[change] add async and sync output processors

---

CHANGELOG.md
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/JVMLanguagePluginParser.kt
server/src/test/java/org/jetbrains/bsp/bazel/server/sync/languages/BUILD
server/src/test/java/org/jetbrains/bsp/bazel/server/sync/languages/JVMLanguagePluginParserTest.kt

fixes https://youtrack.jetbrains.com/issue/BAZEL-154

[fix] `JVMLanguagePluginParser.calculateJVMSourceRoot` does not throw an exception for package longer than the path

---

CHANGELOG.md
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/BspMappings.kt

[fix] `BuildTargetIdentifier` mapping uses `.uri` instead of `.toString`

---

CHANGELOG.md
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/thrift/ThriftLanguagePlugin.kt

Certain thrift generators (scrooge) now put the library source directly on the thrift_library target.  This changes the language plugin to also look at the JavaInfo on the target (if its populated) and get the sources from there as well.

[fix] use source deps from JavaInfo if they are available for thrift targets

---

server/src/main/java/org/jetbrains/bsp/bazel/server/BazelBspServer.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/ServerInitializer.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/bloop/BloopExporter.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelServices.java
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BspServerApi.java
server/src/main/java/org/jetbrains/bsp/bazel/server/common/ServerContainer.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/diagnostics/DiagnosticBspMapper.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/diagnostics/DiagnosticsService.kt
server/src/test/java/org/jetbrains/bsp/bazel/server/diagnostics/DiagnosticsServiceTest.kt

Before this change, `bazel info` was called before the actual BSP
server. This means, there was no clear way to submit failure (for
example if `bazel` executable was not available in PATH). Currently,
it is run on `build/intitialize` request, so the error will be logged
via BSP failure response.

[fix] postpone bazel info

---

server/src/main/java/org/jetbrains/bsp/bazel/server/bloop/BspModuleExporter.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/bloop/BspProjectExporter.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/BspProjectMapper.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/LanguagePluginsService.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/java/JavaModule.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/jvm/JvmModule.kt

It is a prerequisite for my further work.
This PR helps to treat all jvm targets (currently java and scala) in a unified way in terms of their common data, i.e. get and "set" JavaModule.

Refactor get/set for JavaModule

---

WORKSPACE
server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BspServerApi.java

the new bsp version is needed for python impl - we will implement the new endpoints later

[maintenance] bsp version bump

---

server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BspServerApi.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/BazelProjectMapper.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/BspProjectMapper.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/IntelliJProjectTreeViewFix.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/ProjectSyncService.java
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/model/Module.kt
server/src/test/java/org/jetbrains/bsp/bazel/server/bloop/BspModuleExporterTest.kt
server/src/test/java/org/jetbrains/bsp/bazel/server/sync/ProjectStorageTest.kt

I implemented the unused endpoint outputPaths.
It would now be possible to add outputs for each module, though it doesn't make much sense for bazel, but maybe some day we will find a use for it.
Currently are outputs are treated as directories, it can be changed easily when we find another use case for this endpoint that would need files.
I am detecting if workspace root will be visible in IntelliJ (either whole workspace is imported or bsp server is setup at workspace root), if so, we return a synthetic module at workspace root with single resource root pointing to the workspace and 4 output directories pointing to the problematic symlinks.

[feature] exclude bazel-* symlinks

---

server/src/main/java/org/jetbrains/bsp/bazel/server/bep/BepOutput.java

This saves about 10 seconds when refreshing a test project with 10 thousand empty targets.

[change] Initialize the hash sets with the number of elements they are expected to hold

---

server/src/main/java/org/jetbrains/bsp/bazel/server/sync/BazelPathsResolver.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/java/IdeClasspathResolver.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/java/JavaLanguagePlugin.kt
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/model/Label.kt
server/src/test/java/org/jetbrains/bsp/bazel/server/sync/languages/java/BUILD
server/src/test/java/org/jetbrains/bsp/bazel/server/sync/languages/java/IdeClasspathResolverTest.kt
server/src/test/java/org/jetbrains/bsp/bazel/server/sync/model/BUILD
server/src/test/java/org/jetbrains/bsp/bazel/server/sync/model/LabelTest.kt

so we were adding target jar to the dependencies, and because of that 'jump to definition' in ij instead of jumping to the real file in the same module was jumping to the jar

[fix] current target jar is excluded from dependencies - aka jump to definition within a module should work now

---

CHANGELOG.md
executioncontext/projectview/README.md

This PR update the instruction how to use projectview, since bazel-bsp newbie (me 😅 ) misunderstood that `bazel-bsp` will automatically read the `projectview.bazelproject` file.
closing https://youtrack.jetbrains.com/issue/BAZEL-377

[maintenance] Update docs how to use projectview | #BAZEL-377 Done

---

server/src/main/java/org/jetbrains/bsp/bazel/server/bloop/BloopExporter.java

Target names in BEP in bazel 6 aren't prefixed with `@`, which causes a mismatch in comparing the failed targets with project targets.

[fix] Fixup failed target names from BEP in bazel 6+

---

.github/workflows/format.yml
.github/workflows/unit-tests.yml

- java format out
- just unit tests instead of separate per module
GH actions are deprecated anyway since we are migrating to TC, but we need it for a while anyway

[maintenance] GH actions update

---

bazel-steward.yaml

This will use new Bazel Steward feature that creates one PR for group of dependencies.

[maintenance] add grouping for dependencies that share version in Bazel Steward

---

bsp-cli/src/java/org/jetbrains/bsp/cli/BUILD
bsp-cli/src/java/org/jetbrains/bsp/cli/Main.kt
install/src/main/java/org/jetbrains/bsp/bazel/install/BUILD
server/src/main/java/org/jetbrains/bsp/bazel/server/BUILD

The bspcli app aallows users to run arbitrary BSP queries to a BSP server instance that lays in the same process as the app, so they can debug Bazel BSP app running on real-world projects just with IntelliJ's "Debug" button.

[maintenance] Implement BSP CLI

---

CHANGELOG.md
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/java/JdkResolver.kt

Currently JDKs are sorted lexicographically by java home for determinism. Sometimes it can be a problem. when there are 2 JDKs found and one of them is used in nearly all targets and one is used in a few docker related targets that are not relevant. If alphabet is not on your side, you get the wrong JDK (for example wrong architecture) that is not even fetched/resolved fully. 
Since JDK resolving is still a heuristic in bazel-bsp, this change should give more useful results usually.

[fix] prioritize most frequently used JDKs when selecting the project JDK

---

CHANGELOG.md
install/src/main/resources/aspects.bzl

Before this PR, scalac options were only loaded from the rule attributes. Options in the toolchain are then merged in one of rules_scala phases with these options for rules and then target is compiled. 
In short, when global opts are set in toolchain, we don't pick them up.
They are only available in toolchain, but there is no way to get to it (`_scala_toolchain` attribute is not actually the toolchain, but some compiler jars). Only way to get to it is to add it to the toolchains attribute of the aspect, which breaks on workspaces without rules_scala. 
Until preprocessor for aspect file or a plugin system is developed, we can't properly implement it.
I've put the proper implementation in the comment for someone migrating this in the future. 
I found a workaround to inspect the compile …

[fix] collect scalac options from toolchain

---

CHANGELOG.md
aspects/rules/scala/scala_info.bzl
server/src/main/java/org/jetbrains/bsp/bazel/server/sync/languages/scala/ScalaSdkResolver.kt

https://youtrack.jetbrains.com/issue/BAZEL-404/Bazel-Bsp-with-scala-3.1.0-Failed-to-resolve-Scala-SDK-for-project
the solution is kinda ugly, but we will be changing the lang support soon and then we will have to handle all the scala 3 things more gracefully

[fix] now server can obtain scala3 compiler

---

README.md

After 3.0 update the default for targets changed from all to none, which is quite confusing, especially for people who approach this server for the first time.
I propose to extend the example command like I did in this PR, so that user knows how to include all targets or easily adjust it to a different scope. It has the added benefit of showing that `--` is needed to pass arguments to the server.
Alternatively, you may want to clearly mention that one has to open the generated project view and add the desired targets. Current state of readme suggests that it is optional thing.

[maintenance] update quick start command

---

server/src/main/kotlin/org/jetbrains/bsp/bazel/server/bep/BepServer.java
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspCompilationManager.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/ExecuteService.kt

Metals uses this information for managing compilations. Also moves clearing diagnostics from `targetComplete` to `taskFinished`

[feature] add data to taskStart and taskFinished

---

install/src/main/kotlin/org/jetbrains/bsp/bazel/install/cli/CliOptionsProvider.kt
install/src/test/kotlin/org/jetbrains/bsp/bazel/install/cli/CliOptionsProviderTest.kt

In the previous PR I forgot to add a proper parsing option. Now, that's fixed and a test is added.

bugfix: Allow enabled-rules on cli installer

---

server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/ClasspathQuery.kt

Previously, if this happened, we would not get any results to a query as two json results line by line are not valid json.
I am not 100% why this happens, one classpath seems to have paths starting with `bazel-out/k8-fastbuild/bin` and the other with `bazel-out/host/bin`, which I don't really understand, but this should be a good enough workaround
Alternatively, I could just return empty, but in any case we should handle the exception I think.

[fix] Fix issue if classpath query returns more results

---

bazelrunner/src/main/kotlin/org/jetbrains/bsp/bazel/bazelrunner/BazelInfo.kt
bazelrunner/src/test/kotlin/org/jetbrains/bsp/bazel/bazelrunner/BazelReleaseTest.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/paths/BazelPathsResolver.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/BazelProjectMapper.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/ProjectResolver.kt

Second attempt, this time I changed it to looks for the actual @@ or @ label to be available.

[fix] fix the `@@` prefix issue if `bazel.module` and `WORKSPACE` are used together

---

CHANGELOG.md
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/diagnostics/BazelRootMessageParser.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/diagnostics/DiagnosticsParser.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/diagnostics/Scala3CompilerDiagnosticParser.kt
server/src/test/kotlin/org/jetbrains/bsp/bazel/server/diagnostics/DiagnosticsServiceTest.kt

Previously, Scala 3 diagnostics would not be shown since they currently use rendered message, which is a pretty printed diagnostic. Now, I added a separate parser for Scala 3 compiler diagnostics.
Related https://github.com/scalameta/metals/issues/6135

bugfix: Fix showing Scala 3 diagnostics

---

server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/BspProjectMapper.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/DependencyMapper.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/ProjectSyncService.kt
server/src/test/kotlin/org/jetbrains/bsp/bazel/server/sync/BUILD
server/src/test/kotlin/org/jetbrains/bsp/bazel/server/sync/DependencyMapperTest.kt

This would be super useful to use as an alternative to libraries request, which is not standard BSP request.
Tests depends on https://github.com/build-server-protocol/bsp-testkit2/pull/41

feature: Add dependencyModules request support

---

aspects/core.bzl
aspects/rules/scala/scala_info.bzl
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspLanguageExtensionsGenerator.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/BazelProjectMapper.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/TargetInfoReader.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/languages/scala/ScalaLanguagePlugin.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/languages/scala/ScalaSdkResolver.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/proto/bsp_target_info.proto
server/src/test/kotlin/org/jetbrains/bsp/bazel/server/bsp/managers/BazelBspLanguageExtensionsGeneratorTest.kt

This prepares us for changes in `rules_scala` that will allow customizing the Scala version for each target.
In order to achieve that, we can no longer resolve the Scala SDK globally as the maximal version used. We need to use per-target info.
Scala SDK will be still discovered based on the compiler class path.
Now though we will look into an implicit dependency of each target, the `_scalac`.
This change is backward-compatible, as the mentioned data is already available.
It is also forward-compatible with the anticipated cross-build feature of `rules_scala`.
(see: https://github.com/bazelbuild/rules_scala/issues/1290)
The aspect will produce additional data – namely few compiler classpath jars per Scala target.
Perhaps we could review this change in the future to normalize the data back. …

[feature] Resolve Scala SDK independently for each target

---

bazelrunner/src/main/kotlin/org/jetbrains/bsp/bazel/bazelrunner/BazelRunnerBuilder.kt
bazelrunner/src/main/kotlin/org/jetbrains/bsp/bazel/bazelrunner/params/BUILD
bazelrunner/src/main/kotlin/org/jetbrains/bsp/bazel/bazelrunner/params/BazelFlag.kt

Add a global tool_tag for all Bazel invocations from Bazel BSP, which will include the server name and version.  In setups where Bazel telemetry is collected, this will allow Bazel BSP invocations to be easily tracked and segmented out from other Bazel calls.
https://youtrack.jetbrains.com/issue/BAZEL-932

[feature] include tool tag for all Bazel invocations

---

e2e/src/main/kotlin/org/jetbrains/bsp/bazel/BazelBspScalaProjectTest.kt
e2e/src/main/kotlin/org/jetbrains/bsp/bazel/base/BazelBspTestBaseScenario.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/bsp/BspServerApi.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/BspProjectMapper.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/ProjectSyncService.kt

It seems that somehow I missed adding it in the previous PR, which baffles me greatly.
This makes sure that if the client wants to only receive classpath via jvmClasspath request then it's done properly.
I totally missed it in https://github.com/JetBrains/bazel-bsp/pull/542/files

bugfix: Don't send classpath if jvmClasspathReceiver is set to true

---

.teamcity/configurations/bazelBsp/bazelE2eTests.kts
e2e/src/main/kotlin/org/jetbrains/bsp/bazel/BazelBspScalaProjectTest.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/bep/BepServer.kt
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/diagnostics/DiagnosticsService.kt

It seems that it was working at some point but somehow it stopped and I am not 100% sure why.
I noticed two issues currently:
- build target label is sometime missing @ so I add them to the label if we are currently in a target that has them
- the warnings would be cleared sine the build was successful, so remove files with warnings from being cleared.
I added a tests that tries to get the warnings twice in the same build whihc should test this properly.

fix: Fix issues with warnings being cleared too soon

---

MODULE.bazel.lock
server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/TargetInfoReader.kt

Previously, we would choose just use first target info, which could be the default config or not. And if the custom config was not being built by default, we would never get artifacts for that produced.
Now, we always have the same stable order, which as far as I've been testing is starting with the default as if we have multiple JVM targets one is usually a copy of another with longer paths. Though there is no way for sure to know which one is the default.
Alternative I was thinking about was trying to get the shortest output path.
We avoid needed to add support for configurations at this point, which is a much bigger task and would require scoping with the bigger bazel team.

improvement: Sort deterministic if more configurations detected

---

logger/src/main/kotlin/org/jetbrains/bsp/bazel/logger/BspClientTestNotifier.kt

originId was missing from the overall taskStart/taskFinish notifications for testing of each target, so adding it in here.  It's already present for the individual test case start/finish notifications so no change needed there.

Include originId in the taskStart/taskFinish notifications from a test run

---

server/src/main/kotlin/org/jetbrains/bsp/bazel/server/diagnostics/Scala3CompilerDiagnosticParser.kt
server/src/test/kotlin/org/jetbrains/bsp/bazel/server/diagnostics/DiagnosticsServiceTest.kt

It turns out the ---- ending is not always showing up (or it changed) so improved the regex to account for that.

[fix] Allow arbitrary ending to Scala 3 error line
